# Generated by Django 5.2.6 on 2025-09-30 13:38

import blog.upload_paths
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content_markdown',
            field=markdownx.models.MarkdownxField(help_text='Поддерживается вставка изображений и ссылок на Rutube', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.upload_paths.cover_upload_to, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=blog.upload_paths.gallery_upload_to, verbose_name='Изображение'),
        ),
    ]
