# Generated by Django 5.2.6 on 2025-10-01 14:58

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_content_markdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content_markdown',
            field=markdownx.models.MarkdownxField(help_text='Поддерживается вставка изображений и ссылок на Rutube в формате {{ rutube:abcde123456 }}', verbose_name='Контент'),
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.blogpost')),
            ],
            options={
                'unique_together': {('post', 'ip_address')},
            },
        ),
    ]
