# Generated by Django 5.2.6 on 2025-10-03 08:54

import blog.models
import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_content_markdown_postview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('content_markdown', markdownx.models.MarkdownxField(help_text='Поддерживается вставка изображений и ссылок на Rutube в формате {{ rutube:abcde123456 }}', verbose_name='Контент')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=blog.models.about_page_cover_upload_to, verbose_name='Обложка')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Description')),
                ('is_active', models.BooleanField(default=False, help_text='Только одна запись может быть активной', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_pages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Страница «О нас»',
                'verbose_name_plural': 'Страницы «О нас»',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.about_page_gallery_upload_to, verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='blog.aboutpage', verbose_name='Страница «О нас»')),
            ],
            options={
                'verbose_name': 'Изображение на странице «О нас»',
                'verbose_name_plural': 'Галерея страницы «О нас»',
                'ordering': ['order', 'id'],
            },
        ),
    ]
