# Generated by Django 5.2.6 on 2025-10-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutpage_aboutpageimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('post', 'ip_address', 'created_at')},
        ),
    ]
