# Generated by Django 5.2.6 on 2025-10-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Прошёл модерацию'),
        ),
    ]
