# Generated by Django 5.2.7 on 2025-10-22 09:22

import blog.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_is_moderated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postview',
            options={'verbose_name': 'Просмотр поста', 'verbose_name_plural': 'Просмотры постов'},
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(max_length=650, upload_to=blog.upload_paths.gallery_upload_to, verbose_name='Изображение'),
        ),
    ]
