# Generated by Django 5.2.7 on 2025-10-26 13:07

import blog.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_postview_options_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=650, null=True, upload_to=blog.upload_paths.cover_upload_to, verbose_name='Обложка'),
        ),
    ]
