# Generated by Django 5.2.7 on 2025-10-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpost_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Description'),
        ),
    ]
